app_identifier "com.nilehanov.compose"
username "nile.hanov@gmail.com"
team_id "KWQTH8W4TL"

copyright "2026 Nile Hanov"
primary_category "PRODUCTIVITY"
price_tier 8

skip_binary_upload true
force true
overwrite_screenshots true
precheck_include_in_app_purchases false
run_precheck_before_submit false

submission_information({
  add_id_info_uses_idfa: false,
  export_compliance_uses_encryption: false,
  content_rights_contains_third_party_content: false
})
